---
editor: visual
bibliography: "icils_nudos.bib"
csl: "apa6.csl"
---

# Introduction

With the proliferation of digital technologies, educational systems worldwide have undergone a deep transformation, where knowledge and abilities in the realm of information and computer technology (ICT) emerge as crucial for navigating modern society. ICT encompass a range of competencies, including —but not limited to— computer literacy, coding skills, internet navigation, and critical thinking in digital environments. In such a context, proficiency in ICT is increasingly recognized as a fundamental component of education success and future career opportunities [@hooleyRoleDigitalTechnology2020;@mahmudDigitalAgeImportance2022]. Despite the widespread integration of technology in classroom instruction, significant disparities persist in the acquisition and mastery of ICT competences among school-age children, contributing unequal access and outcomes that hinder the ability of marginalized groups to fully participate and succeed in an increasingly digital society [@dodelSocioeconomicInequalitiesDigital2021]. 

A primary factor that generates gaps in ICT competences is socioeconomic status, whereby children from lower-income families often face barriers such as limited access to reliable internet connectivity, outdated technology infrastructure in schools, and insufficient resources for digital learning tools [@butcherDigitalPovertyBarrier2022;@mulyaningsihPovertyDigitalDivide2021]. Additionally, disparities in parental education and involvement further exacerbate these challenges, as children from families with higher levels of parental education tend to have greater exposure to technology and receive more support for developing ICT knowledge and skills [@oharaYoungChildrenICT2011]. Furthermore, cultural stereotypes and gender norms can also influence the types of skills encouraged and valued among boys and girls, leading to differential opportunities for learning and advancement in certain domains [@claytonGenderStereotypesPrevail2009;@wongTechnicalBoysCreative2018].  For instance, girls are less likely to pursue computer science and engineering degrees due to stereotypes that these fields are male-oriented [@cheryanCulturalStereotypesGatekeepers2015]. Such stereotypes emerge very early and are reinforced in socialization environments such as the school [@varoyUnderstandingGenderGap2023]. 

Besides status and gender differences in the acquisition of ICT knowledge and skills, self-efficacy has proven to be a key aspect in the exercise of digital competences. Self-efficacy is generally defined as a person's confidence in their capacity to handle challenges and achieve desired outcomes [@banduraSelfefficacyMechanismHuman1982], essential for an adequate exercise of digital skills. Research suggests that societal stereotypes and cultural norms often shape individuals' perceptions of their digital self-efficacy and interests in technology domains, which can vary based on gender [@hargittaiDifferencesActualPerceived2006]. Girls, for instance, may internalize messages that associate technology and computer science with masculine traits, leading to lower confidence in their abilities and less motivation to pursue digital learning opportunities [@papastergiouAreComputerScience2008]. Conversely, boys may receive implicit or explicit encouragement to engage with technology, resulting in higher levels of self-efficacy and persistence in acquiring digital skills. Furthermore, socialization within peer groups and family environments can reinforce these gendered attitudes, creating a self-perpetuating cycle of differential participation and achievement in digital domains that could have an impact in perceptions of self-efficacy. 

Chile presents particularly interesting conditions for studying gender inequalities in digital self-efficacy around educational contexts. In this country, although female enrolment in higher education exceeds male enrolment by 6.9%, in the case of degrees associated with computer technologies, male enrolment exceeds female by 65.7% [@siesInforme2021Matricula2021;@guzmanBrechasGeneroEducacion2021]. In addition, there is evidence of high levels of dropout among women entering computer careers, which are mainly explained by psychological factors such as low self-esteem, academic inefficiency and lack of encouragement during their secondary education [@gonzalezcatalanDesercionEstudiantilEducacion2018;@delafuente-mellaAnalysisPredictionEngineering2020]. This last finding is in line with research showing a persistent gender gap in performance on standardized mathematics national school tests [@vargasdiazBrechasPersistentesGenero2022]. In this sense, and in line with the findings of the educational literature in the Latin American region, it is important to approach the school stage in order to understand the formation of gender inequalities in self-efficacy and digital literacy around higher education and occupational structure [@ancheta-arrabalGenderDigitalDivide2021].

The present paper deals with Chile’s gender differences regarding digital literacy at school age, with a focus on ICT self-efficacy in three main aspects. First, we make a distinction between general and specific digital self-efficacy in order to explore whether sex differences manifest equally in both domains. Secondly we address the link between ICT knowledge and self-efficacy by gender. The interest in this aspect is based on the fact that girls tend to outperform their male counterparts when it comes to standardized test in technological abilities and literacy [@gebhardtGenderDifferencesComputer2019;@tomteGenderdifferencesSelfefficacyICT2011;@tsaiJuniorHighSchool2010;@punterGenderDifferencesComputer2017;@fraillonPreparingLifeDigital2014]. Therefore, this would express a paradox for girls: subestimation in self-efficacy despite better performance. Thirdly, we focus on class gender composition and its interaction with gender and self-efficacy. Based on research on gender compositional effects in classrooms, we argue that the interaction in contexts with peers with higher self-efficacy (males) could lead to a reinforcement of gender stereotypes and to a decrease in ITC self-efficacy in females. Therefore, a larger proportion of females in a classroom would be related to larger self-efficacy for them.
