---
editor: visual
---

# Self-efficacy and ICT (Information and Computer Technology)

One key psychological construct related to ICT is self-efficacy. Developed by 
@banduraSelfefficacyMechanismHuman1982, self-efficacy refers to “beliefs in one’s capabilities to organize and execute the courses of action required to produce given attainments” (p. 3). In other words, it is a form of self-assessment or perception of one’s own abilities, shaping individuals’ decisions and choices. Those who believe that they are capable of performing well in an activity are more likely to put in effort, as well as persist and persevere when they experience obstacles [@banduraSelfefficacyMechanismHuman1982]. As a component of social cognitive theory, self-efficacy distinguishes between people’s motivation to perform a task based on the expected outcome (outcome expectancy) and their perceived capability to perform a task (self-efficacy). As @banduraSelfefficacyUnifyingTheory1977 put it: “Individuals can believe that a particular course of  action will produce certain outcomes, but if they entertain serious doubts about whether they can perform the necessary activities such information does not influence their behavior” (p.193). As such, it is usually positioned early in the chain of predictors that determines performance and behaviors and has become a very relevant  factor to determine learning processes and performances in different areas such as education [@wrayFactorsInfluencingTeacher2022] and health [@mataTrainingCommunicationSkills2021]. 

According to the theory and evidence [@banduraSelfefficacyExerciseControl1997;@usherSelfefficacySelfregulatedLearning2008], there are four sources of self-efficacy, which can be grouped into individual factors (mastery experience and emotional states)  and social comparative factors (vicarious experiences and social model) considered sources of self-efficacy. Mastery experience refers to people’s previous interpretations and evaluations of their successes and failures completing similar or related tasks. Experienced mastery (or previous skills) has a strong effect on people’s self-efficacy. Also, negative emotional states such as anxiety and stress undermine self-efficacy. 

Self-efficacy has proven to be particularly relevant when it comes to digital technologies. Several concepts have been used to describe people’s abilities and performance in this realm,  such as digital skills [@correaDigitalSkillsSocial2016;@vandijkDigitalSkillsUnlocking2014], digital competence [@zhaoDigitalCompetenceHigher2021], information and communication technologies (ICT) literacy, or digital literacy [@reddyDigitalLiteracyReview2020], among others. Much of these concepts has been used in an applied science approach, which has focused on technical abilities regarding hardwares and softwares. However, more recent frameworks have emphasized the need to focus on digital abilities that involve critical thinking as well as social and creative skills (REF Helpser, 2023; REF Correa, Valenzuela, & Pavez, 2023). For instance, @vandijkDigitalSkillsUnlocking2014 as well as REF Helsper and colleagues (2020) have distinguished among different dimensions: technical and operational skills; information navigation and processing skills; communication and interaction skills; and content creation and production skills. 

A more specific definition of ICT competences for the school-age has been developed by @fraillonPreparingLifeDigital2014 in the framework of the International Computer and Information Literacy Study (hereafter ICILS). ICILS is an international comparative study conducted by the IEA (International Association for the Evaluation of Educational Achievement) since 2013, with further waves in 2018 and 2023 (still not released). ICILS has used the term “computer and information literacy” (CIL) to describe people’s “ability to investigate, create, and communicate in order to participate effectively at home, at school, in the workplace, and in society to use computers to investigate [@fraillonPreparingLifeDigital2014]. Following a multidimensional approach, the CIL assessment focuses on computers and encompasses four strands of skills: understanding computer use, gathering information, producing information, and digital communication. The 2018 study followed the same conceptualization and included computer thinking [@fraillonPreparingLifeDigital2020]. Although the vast majority of studies have focused on self-reported levels of skills [@livingstoneOutcomesGainingDigital2023], the ICILS study measured students’ performance by completing a range of tasks.  

Combining the previous definitions of self-efficacy and digital literacy, it is possible to define digital self-efficacy as the individuals’ belief in their ability to perform specific actions on computer or information technologies to achieve a particular goal [@eastinInternetSelfEfficacyPsychology2000]. Although there are several terms and ways of measuring this construct [@cassidyDevelopingComputerUser2002a], the evidence has consistently shown that digital self-efficacy is a strong predictor of various digital competencies, including frequency of internet usage among adolescents, especially among male teens [@broosDigitalDividePlaystation2006], and number of online activities performed [@livingstoneGradationsDigitalInclusion2007]. 

Research has also distinguished between general and specific self-efficacy. While the former refers to more general beliefs or feelings in one’s abilities toward basic tasks, the former is related to more specific tasks [@agarwalResearchReportEvolving2000]. General self-efficacy is not necessarily tied to specific situations, could be built on previous experiences and conceived as a more general dispositions [@schwoererGeneralSpecificSelfEfficacy2005].

Another relevant aspect to consider for developing ICT self-efficacy is the level of knowledge about these technologies, which can be placed as mastery experience. Previous evidence shows that getting training [@downeyLongitudinalExaminationEffects2015], receiving standard classes in a computer science course (ADD REF), and having more experience using ICTs [@hatlevikStudentsICTSelfefficacy2018] can increase self-efficacy levels. Along the same lines, evidence in the school population shows that computer literacy —which mainly focuses on evaluating basic tasks— is positively associated with ICT self-efficacy. Here too, it is possible to distinguish between self-efficacy for either basic or advanced tasks. Specifically, higher computer literacy increases basic ICT self-efficacy but not advanced ICT self-efficacy [@fraillonPreparingLifeDigital2020]. An important aspect to consider is that computer literacy also shows gender gaps. Cross-national results from international studies show that girls tend to achieve higher proficiency levels than boys in computer literacy [@fraillonPreparingLifeDigital2014].
