---
editor: visual
---

# Gender and Self-efficacy

Gender differences in ICT self-efficacy is a widely studied topic. Empirical evidence consistently shows girls tend to feel less confident than boys in their ability to use ICTs [@broosGenderInformationCommunication2005;@gebhardtGenderDifferencesComputer2019;@hargittaiDifferencesActualPerceived2006]. Similarly, gender differences have been observed in multiple aspects of the digital sphere, such as women’s participation gaps in the technology sector, attitudinal gaps toward ICTs access, interest and enjoyment of technologies, computer use intention for study and labor, among others [@hargittaiMindSkillsGap2015;@lopez-martinezDigitalGenderDivide2021;@schradieGenderedDigitalProduction2015]. Most theories attempting to explain such gender differences in confidence and skills are related to conceptualizations of prejudices and stereotypes about gender, which at the same time can affect individual perceptions of self-efficacy.

Stereotypes are beliefs about the characteristic properties of people classified into particular social categories or groups. Because they are shared and acquired within societies, they can shape social life and affect the way we treat individuals, who are expected to have certain traits, role behaviors, occupations, and physical characteristics based on attributes such as gender, ethnicity, or age [@eaglyViciousCycleLinking2021;@eaglyGenderStereotypesHave2020;@hainesTimesTheyAre2016]. Gender stereotypes are generalizations about the attributes of men and women, and have both descriptive and prescriptive properties, designating both what women and men are like, and should be like [@eaglyRoleCongruityTheory2002;@heilmanDescriptionPrescriptionHow2001;@heilmanGenderStereotypesWorkplace2012]. Among these ideas are that men are rational, assertive, active, unfeeling and perform well in physical work, whereas women are emotional, indecisive, passive, warm, physically weak but nurturing [@eaglyRoleCongruityTheory2002;@ellemersGenderStereotypes2018]. These traits translate into work domains and expected roles and, for instance, women are more often associated with arts and family, and men with science and physical labor [@hainesTimesTheyAre2016;@heilmanGenderStereotypesWorkplace2012;@tellhedTechSavvyMenCaring2023].

While gender stereotypes are not static, they have shown to inform expectations about men and women’s interests and talents, and even people’s career aspirations [@ellemersGenderStereotypes2018;@hainesTimesTheyAre2016]. This includes expectancies of success —that is, self-efficacy. In general, girls and women show low levels of self-efficacy in stereotypically male activities and men-dominated domains, including technology and computer sciences spaces, even when their actual performance is not necessarily worse [@beyerWhyAreWomen2014;@broosGenderInformationCommunication2005;@gebhardtGenderDifferencesComputer2019]. 

Various theories have attempted to understand the gender gap, considering self-efficacy consistent with the gender stereotypes framework. For instance, the Expectancy-Value Theory (EVT) “postulates that achievement-related choices are motivated by a combination of people's expectations for success and subjective task value in particular domains” [@leaperChapterMoreSimilarities2011a]. In it, expectation of doing well (combined with the value of the activity) could make it more likely to be involved in activities. Similarly, the Stereotype Threat Theory (STT) poses the expectation of performance in the center. It proposes that when there is a stereotype about the poor performance of a minority group in a relevant task, members of that group tend to confirm the stereotype, particularly in more complex tasks [@kochWomenComputersEffects2008]. In this case, women tend to be perceived as worse performers in computer use [@smithInvestigatingMeasureComputer2005], which would be consistent with the results observed in interest or ICT self-efficacy. Aligned with social modelling sources of self-efficacy, the Social Role Theory (SRT) argues that gender stereotypes derived from the roles that men and women occupy in society can affect achievement expectations, ability beliefs, or interests [@tellhedTechSavvyMenCaring2023]. From the SRT, the fact that ICTs are associated with more masculine traits affects interest and expectations in studying and participating in ICT-related occupations [@sainzGenderStereotypesAttitudes2016a;@calabuigEffectsIntensiveUse2018]. Girls tend to perceive work in ICTs as antisocial, very technical, detached from social needs, lacking social skills and individualistic [@thomasGenderDifferencesStudents2006;@sainzParentalSecondarySchool2012], which would diverge from stereotypes associated with women. Along these lines, it is argued that girls have less exposure to female roles that could model their participation in ICTs. Specifically, it has been observed that there are fewer examples of women in the ICT field among families and teachers and that they also tend to have a stereotyped opinion of them [@cusso-calabuigEffectsIntensiveUse2018].
 
As the STT suggests [@kochWomenComputersEffects2008;@masterCulturalStereotypesSense2020], confirmation tends to occur with more difficult tasks. By distinguishing between basic ICTs versus more complex tasks requiring more training, boys tend to show even greater self-efficacy than girls in advanced tasks [@buschGenderDifferencesSelfEfficacy1995]. For @cassidyDevelopingComputerUser2002a, a possible explanation is that more complex tasks tend to be perceived as more masculine, which would partly explain the observed result. In contrast, @hatlevikStudentsICTSelfefficacy2018 report that girls show higher levels of self-efficacy in ten out of fourteen analyzed countries, concluding that the image of boys being more self-confident than girls could be decreasing in some countries. However, it is relevant to mention that the analyzed self-efficacy scale refers to basic tasks, such as editing text or finding internet information [@fraillonPreparingLifeDigital2020].
 
In sum, evidence points to higher self-efficacy of boys compared to girls, but also higher achievement by girls, which posits the question of how these two factors interact. Evidence suggests that boys tend to overestimate their own ICT literacy, while girls tend to underestimate it [@punterGenderDifferencesComputer2017]. Consequently, the expected interaction is that higher computer literacy would increase gender gaps in ICT self-efficacy. In that case, high levels of achievement could increase the boys’ confidence in their ICT abilities, and conversely, low levels of achievement could decrease girls’ confidence in ICT abilities.

Arguably, gender socialization and stereotypes influence the types of activities boys and girls practice, their interests, and the achievements they may accomplish, which reflects and perpetuates gender roles and gender gaps. Therefore, we posit the following hypotheses:

-   H1: Female students will show lower digital self-efficacy than male students.
-   H2: As computer literacy increases, digital self-efficacy will increase.
-   H3: When computer literacy increases, female students will have a lower increase of digital self-efficacy than males.
